name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '30 18 * * 0,3'  # 3:30 AM JST Monday and Thursday
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.15.1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.11.0
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Fetch latest episodes
        run: node scripts/fetch-episodes.js

      - name: Build
        run: pnpm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist